package postgres

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/MastewalB/behemoth/migration/core"
	_ "github.com/lib/pq"
)

func init() {
	pgdb := &PostgreSQLDriver{}
	core.Register("postgres", pgdb)
	core.Register("postgresql", pgdb)
}

type PostgreSQLDriver struct {
	db     *sql.DB
	config *core.Config
}

func WithInstance(ctx context.Context, db *sql.DB, config *core.Config) (core.Driver, error) {
	if err := db.PingContext(ctx); err != nil {
		return nil, err
	}

	return &PostgreSQLDriver{
		db:     db,
		config: config,
	}, nil
}

func (pgd *PostgreSQLDriver) CreateTable(ctx context.Context, name string, schema *core.TableSchema) error {

	query := CreatePGTable(schema)
	_, err := pgd.db.ExecContext(ctx, query)
	return err
}

func (pgd *PostgreSQLDriver) DropTable(ctx context.Context, name string) error {

	query := fmt.Sprintf("DROP TABLE IF EXISTS %s", name)
	_, err := pgd.db.ExecContext(ctx, query)
	return err
}

func (pgd *PostgreSQLDriver) AddColumn(ctx context.Context, table, column, columnType string) error {

	query := fmt.Sprintf("ALTER TABLE %s ADD COLUMN %s %s", table, column, columnType)
	_, err := pgd.db.ExecContext(ctx, query)
	return err
}

func (pgd *PostgreSQLDriver) RemoveColumn(ctx context.Context, table, column string) error {

	query := fmt.Sprintf("ALTER TABLE %s DROP COLUMN IF EXISTS %s", table, column)
	_, err := pgd.db.ExecContext(ctx, query)
	return err
}

func (pgd *PostgreSQLDriver) CreateMigrationTable(ctx context.Context) error {
	query := `
		CREATE TABLE IF NOT EXISTS schema_migrations (
			version INTEGER PRIMARY KEY,
			applied_at DATETIME DEFAULT CURRENT_TIMESTAMP
		)
	`

	_, err := pgd.db.ExecContext(ctx, query)
	return err
}

func (pgd *PostgreSQLDriver) Open(config *core.Config) (core.Driver, error) {

	dbInstance := config.DB
	if dbInstance == nil {
		return nil, fmt.Errorf("sql db instance is required")
	}

	db, ok := dbInstance.(*sql.DB)
	if !ok {
		return nil, fmt.Errorf("unknown sql db instance provided")
	}

	return WithInstance(context.Background(), db, config)
}

// Run executes raw migration string
func (pgd *PostgreSQLDriver) Run(ctx context.Context, migration string) error {

	_, err := pgd.db.ExecContext(ctx, migration)
	return err
}

// Version returns the currently active version.
// When no migration has been applied, it must return version -1.
func (pgd *PostgreSQLDriver) Version(ctx context.Context) (version int, err error) {

	err = pgd.db.QueryRowContext(ctx, "SELECT version FROM schema_migrations LIMIT 1").Scan(&version)
	if err == sql.ErrNoRows {
		return -1, nil
	}

	return version, err
}

func (pgd *PostgreSQLDriver) SetVersion(ctx context.Context, version int) error {
	_, err := pgd.db.ExecContext(ctx, "UPDATE schema_migrations SET VERSION = $1", version)
	return err
}

func (pgd *PostgreSQLDriver) Close() error {
	return pgd.db.Close()
}

func (pgd *PostgreSQLDriver) Ping(ctx context.Context) error {

	return pgd.db.PingContext(ctx)
}

func (pgd *PostgreSQLDriver) Name() string {

	return "postgres"
}

func CreatePGTable(tableSchema *core.TableSchema) string {

	var query strings.Builder

	fmt.Fprintf(&query, "CREATE TABLE IF NOT EXISTS %s (", tableSchema.Name)

	for i, col := range tableSchema.Columns {

		//Apply column overrides if any exist
		if ov, ok := col.Overrides["postgres"]; ok {
			col.Type = ov.Type
			if ov.Default != "" {
				col.Default = ov.Default
			}

			if ov.Check != "" {
				col.Check = ov.Check
			}

			if ov.AutoInc != nil {
				col.AutoInc = *ov.AutoInc
			}

		}

		if i > 0 {
			query.WriteString(",")
		}

		fmt.Fprintf(&query, " %s %s", col.Name, getPGColumnType(col))
		if col.Primary {
			query.WriteString(" PRIMARY KEY")
		}

		if col.AutoInc {
			// After PostgreSQL 10, it's recommended to use the identity column "generated as identity".
			// The alternative way of using serials is discouraged (https://wiki.postgresql.org/wiki/Don%27t_Do_This#Don.27t_use_serial)
			//
			// We will use "GENERATED BY DEFAULT" since the alternative "GENERATED ALWAYS" will return an error if a value if provided for the column.
			query.WriteString(" GENERATED BY DEFAULT AS IDENTITY")
		}

		if !col.Nullable {
			query.WriteString(" NOT NULL")
		}

		if col.Unique && !col.Primary {
			query.WriteString(" UNIQUE")
		}

		if col.Default != "" {
			fmt.Fprintf(&query, " DEFAULT %s", col.Default)
		}

		if col.Check != "" {
			fmt.Fprintf(&query, " CHECK (%s)", col.Check)
		}
	}

	query.WriteString(" )")
	return query.String()
}

func getPGColumnType(col core.Column) string {
	switch col.Type {

	case core.Integer:
		return "INTEGER"

	case core.Real:
		return "DOUBLE PRECISION"

	case core.Numeric:
		return "NUMERIC"

	case core.BigInt:
		return "BIGINT"

	case core.Text:
		return "TEXT"

	case core.Uuid:
		return "UUID"

	case core.Blob:
		return "BYTEA"

	case core.Json:
		return "JSONB"

	case core.DateTime:
		return "TIMESTAMP"

	case core.Boolean:
		return "BOOLEAN"

	default:
		return "TEXT"
	}

}
